spring.application.name=rencontres
server.port=8080

# MongoDB Configuration (SANS authentification)
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=socialmeetup

# Neo4j Configuration
spring.neo4j.uri=bolt://localhost:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=password //mdp de neo4j dans docker-compose.yml

# Redis Configuration (SANS mot de passe)
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Elasticsearch Configuration
spring.elasticsearch.uris=http://localhost:9200
spring.elasticsearch.connection-timeout=5s
spring.elasticsearch.socket-timeout=60s

# Swagger/OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# Logs
logging.level.com.project.socialmeetup=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.springframework.data.neo4j=DEBUG